name: matt.mercurio
favicon: null
layout_spectrum: 0.06138868792913854
typography_spectrum: 0.8231988123152405
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.2851361248176545
  lightness: 0.33204329293221235
  saturation: 0.28652961691841483
  rhythmicContrast: 0.8468832783401012
purpose: []
